name:                 logic-engine
version:              0.1.0.0
visibility:           public
id:                   logic-engine-0.1.0.0-inplace
key:                  logic-engine-0.1.0.0-inplace
abi:                  inplace
exposed:              True
exposed-modules:
    AtomicEvaluation AtomicParser AtomicPerformative
    AtomicPropertyCheck AtomicPropertyQuery AtomicSentence Console
    Grammar Ontology Pretty ReferenceResolution Result Sandbox

import-dirs:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/build

library-dirs:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/build

library-dirs-static:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/build

dynamic-library-dirs:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/build

data-dir:             /home/peter/dev/logic_chatbot/backend/logic_engine/.
hs-libraries:         HSlogic-engine-0.1.0.0-inplace
depends:
    base-4.20.2.0-f074
    megaparsec-9.8.3-6f286ff4dff7acbc7c9742ccf3d62959a330c6e490e35b12503614047b695f47

haddock-interfaces:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/doc/html/logic-engine/logic-engine.haddock

haddock-html:
    /home/peter/dev/logic_chatbot/backend/logic_engine/dist-newstyle/build/x86_64-linux/ghc-9.10.3/logic-engine-0.1.0.0/doc/html/logic-engine
